spring.application.name=E-Commerce

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ckesbyvsqkcbwoytwths
spring.datasource.password=********

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true